ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1001
ARG PGID=1001
#
RUN addgroup -g ${PGID} -S alpine && \
    adduser -u ${PUID} -G alpine -h /home/alpine -D alpine
RUN set -xe \
    && apk add --no-cache --purge --virtual .build-deps -uU libc-dev libffi-dev linux-headers build-base \
    && apk add --no-cache --purge -uU curl ca-certificates tzdata ruby ruby-dev ruby-irb ruby-bigdecimal \
    && echo 'gem: --no-document' > /etc/gemrc \
    && echo 'install: --no-document' >> /etc/gemrc \
    && echo 'update: --no-document' >> /etc/gemrc \
# Install and upgrade packages
    && gem install bundler json rake \
    && gem cleanup \
    && apk del --purge .build-deps \
    && apk add --no-cache git \
    && rm -rf /usr/lib/ruby/gems/*/cache/* \
    && rm -rf /var/cache/apk/* /tmp/*
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/usr/bin/ruby"]
